# Generated by Django 2.1.3 on 2018-11-29 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20181129_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2018, 12, 6, 20, 35, 59, 903174), verbose_name='due date'),
        ),
    ]
