# Generated by Django 2.1.3 on 2018-12-05 02:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20181129_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='due date'),
        ),
    ]
